# Generated by Django 6.0.3 on 2026-05-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hazards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
                ('formula', models.CharField(blank=True, max_length=80, verbose_name='Fórmula química')),
                ('cas_number', models.CharField(blank=True, help_text='Chemical Abstracts Service registry number (ex: 7647-01-0).', max_length=20, verbose_name='Número CAS')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('physical_state', models.CharField(choices=[('solid', 'Sólido'), ('liquid', 'Líquido'), ('gas', 'Gás'), ('aqueous', 'Solução aquosa')], default='liquid', max_length=10, verbose_name='Estado físico')),
                ('molar_mass', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Massa molar (g/mol)')),
                ('ph_value', models.DecimalField(blank=True, decimal_places=2, help_text='Quando aplicável a soluções aquosas.', max_digits=4, null=True, verbose_name='pH (aprox.)')),
                ('is_acid', models.BooleanField(default=False, verbose_name='É ácido')),
                ('is_base', models.BooleanField(default=False, verbose_name='É base')),
                ('is_water', models.BooleanField(default=False, verbose_name='É água')),
                ('is_organic_solvent', models.BooleanField(default=False, verbose_name='Solvente orgânico')),
                ('required_ppe', models.JSONField(blank=True, default=list, help_text='Lista de EPIs (ex: ["luvas nitrílicas", "óculos de proteção"]).', verbose_name='EPIs recomendados')),
                ('handling_notes', models.TextField(blank=True, verbose_name='Cuidados ao manipular')),
                ('critical_alerts', models.TextField(blank=True, help_text='Avisos de segurança que devem aparecer em destaque.', verbose_name='Alertas críticos')),
                ('storage_instructions', models.TextField(blank=True, verbose_name='Instruções de armazenamento')),
                ('storage_incompatibilities', models.TextField(blank=True, help_text='Substâncias / classes que não podem ser estocadas próximas.', verbose_name='Incompatibilidades de armazenamento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('hazards', models.ManyToManyField(blank=True, related_name='substances', to='hazards.hazard', verbose_name='Riscos')),
            ],
            options={
                'verbose_name': 'Substância',
                'verbose_name_plural': 'Substâncias',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='substances__name_c774d2_idx'), models.Index(fields=['cas_number'], name='substances__cas_num_9c9870_idx'), models.Index(fields=['is_active'], name='substances__is_acti_db79fc_idx')],
            },
        ),
    ]
