# Generated by Django 6.0.3 on 2026-05-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('flammable', 'Inflamável'), ('corrosive', 'Corrosivo'), ('toxic', 'Tóxico'), ('oxidizer', 'Oxidante'), ('reactive_water', 'Reage com água'), ('explosive', 'Explosivo'), ('irritant', 'Irritante'), ('carcinogen', 'Carcinogênico'), ('env_hazard', 'Perigoso ao meio ambiente'), ('compressed_gas', 'Gás comprimido')], help_text='Identificador estável usado pelo motor de regras.', max_length=30, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=80, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('default_severity', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='medium', max_length=10, verbose_name='Severidade padrão')),
                ('pictogram', models.CharField(blank=True, help_text='Nome do ícone (lucide-react) usado no frontend.', max_length=50, verbose_name='Pictograma (ícone)')),
            ],
            options={
                'verbose_name': 'Risco',
                'verbose_name_plural': 'Riscos',
                'ordering': ['name'],
            },
        ),
    ]
