# Generated by Django 6.0.3 on 2026-05-02 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('substances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('safe', 'Seguro'), ('unsafe', 'Não seguro'), ('unknown', 'Desconhecido')], default='unknown', max_length=20, verbose_name='Status')),
                ('risk_level', models.CharField(choices=[('low', 'Baixo'), ('medium', 'Médio'), ('high', 'Alto')], default='low', max_length=10, verbose_name='Nível de risco')),
                ('reaction_type', models.CharField(blank=True, help_text="Ex: 'Reação exotérmica', 'Liberação de gás tóxico'.", max_length=120, verbose_name='Tipo de reação')),
                ('notes', models.TextField(blank=True, help_text='Detalhes técnicos, referências e cuidados específicos.', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('substance_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_records_as_a', to='substances.substance', verbose_name='Substância A')),
                ('substance_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_records_as_b', to='substances.substance', verbose_name='Substância B')),
            ],
            options={
                'verbose_name': 'Registro de compatibilidade',
                'verbose_name_plural': 'Registros de compatibilidade',
                'ordering': ['substance_a__name', 'substance_b__name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('substance_a__lt', models.F('substance_b'))), name='compat_pair_normalized')],
                'unique_together': {('substance_a', 'substance_b')},
            },
        ),
    ]
