# Generated by Django 6.0.3 on 2026-05-02 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('substances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FISPQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(choices=[('manual', 'Cadastro manual'), ('pubchem', 'PubChem'), ('echa', 'ECHA (European Chemicals Agency)'), ('manufacturer', 'Fabricante')], default='manual', max_length=20, verbose_name='Fonte dos dados')),
                ('source_url', models.URLField(blank=True, help_text='Link para o registro original (ex: PubChem CID page).', verbose_name='URL da fonte')),
                ('revision_date', models.DateField(blank=True, help_text='Data da última revisão da FISPQ na fonte original.', null=True, verbose_name='Data de revisão')),
                ('is_complete', models.BooleanField(default=False, help_text='Indica se todas as seções relevantes foram preenchidas.', verbose_name='Dados completos')),
                ('ghs_classification', models.JSONField(blank=True, default=list, help_text='Lista de classes de perigo GHS (ex: ["Flam. Liq. 2", "Acute Tox. 4"]).', verbose_name='Classificação GHS')),
                ('signal_word', models.CharField(blank=True, help_text="'Perigo' ou 'Atenção' (Danger / Warning).", max_length=20, verbose_name='Palavra de sinalização')),
                ('h_phrases', models.JSONField(blank=True, default=list, help_text='Ex: [{"code": "H225", "text": "Líquido e vapor altamente inflamáveis"}].', verbose_name='Frases H (perigo)')),
                ('p_phrases', models.JSONField(blank=True, default=list, help_text='Ex: [{"code": "P210", "text": "Manter afastado de fontes de calor..."}].', verbose_name='Frases P (precaução)')),
                ('ghs_pictograms', models.JSONField(blank=True, default=list, help_text='Códigos dos pictogramas (ex: ["GHS02", "GHS07"]).', verbose_name='Pictogramas GHS')),
                ('flash_point', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Ponto de fulgor (C)')),
                ('auto_ignition_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Temperatura de autoignição (C)')),
                ('extinguishing_media', models.JSONField(blank=True, default=list, help_text='Ex: ["CO2", "espuma", "pó químico"].', verbose_name='Meios de extinção')),
                ('handling_precautions', models.TextField(blank=True, verbose_name='Precauções de manuseio')),
                ('storage_conditions', models.TextField(blank=True, verbose_name='Condições de armazenamento')),
                ('incompatible_materials', models.JSONField(blank=True, default=list, help_text='Lista de materiais/classes incompatíveis para armazenamento.', verbose_name='Materiais incompatíveis (Seção 7)')),
                ('oel_ppm', models.DecimalField(blank=True, decimal_places=3, help_text='OEL / TWA em ppm (quando aplicável).', max_digits=10, null=True, verbose_name='Limite de exposição (ppm)')),
                ('oel_mg_m3', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Limite de exposição (mg/m3)')),
                ('recommended_ppe', models.JSONField(blank=True, default=list, verbose_name='EPIs recomendados (FISPQ)')),
                ('boiling_point', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Ponto de ebulição (C)')),
                ('melting_point', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Ponto de fusão (C)')),
                ('density', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='Densidade (g/cm3)')),
                ('vapor_pressure', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Pressão de vapor (mmHg a 25C)')),
                ('solubility_water', models.CharField(blank=True, help_text="Ex: 'miscível', 'insolúvel', '35 g/L a 20C'.", max_length=120, verbose_name='Solubilidade em água')),
                ('log_p', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='LogP (coef. partição octanol/água)')),
                ('stability_notes', models.TextField(blank=True, help_text='Condições normais de estabilidade.', verbose_name='Estabilidade')),
                ('conditions_to_avoid', models.JSONField(blank=True, default=list, help_text='Ex: ["calor", "faíscas", "umidade"].', verbose_name='Condições a evitar')),
                ('incompatible_chemicals', models.JSONField(blank=True, default=list, help_text='Substâncias/classes com reação perigosa (ex: ["oxidantes fortes", "ácidos"]).', verbose_name='Substâncias incompatíveis (Seção 10)')),
                ('hazardous_decomposition', models.JSONField(blank=True, default=list, help_text='Ex: ["CO", "CO2", "vapores tóxicos"].', verbose_name='Produtos de decomposição perigosos')),
                ('ld50_oral', models.CharField(blank=True, help_text="Ex: '7060 mg/kg (rato)'.", max_length=80, verbose_name='DL50 oral')),
                ('lc50_inhalation', models.CharField(blank=True, max_length=80, verbose_name='CL50 inalação')),
                ('pubchem_cid', models.PositiveIntegerField(blank=True, help_text='Compound ID no PubChem (para rastreabilidade).', null=True, unique=True, verbose_name='PubChem CID')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='JSON completo retornado pela API (auditoria).', verbose_name='Dados brutos da fonte')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('substance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fispq', to='substances.substance', verbose_name='Substância')),
            ],
            options={
                'verbose_name': 'FISPQ',
                'verbose_name_plural': 'FISPQs',
                'ordering': ['substance__name'],
            },
        ),
    ]
